---
title: "Where to Stay"
---

We contacted a few hotels about room blocks, but none of them provided competitive discounts. Since the rate for hotels has a wide range on big island, we decided not to reserve a room block so our guests could feel free to choose where to stay. There are a variety of lodging options close to the venue. Our price information below is as of October 2023, before taxes and fees.

## Within walking distance:

-   [**Royal Kona Resort**](https://www.google.com/maps/place/Royal+Kona+Resort/@19.6321144,-155.9928887,17z/data=!3m1!4b1!4m9!3m8!1s0x79540f02e3d1ed53:0xecbc48d326c5655d!5m2!4m1!1i2!8m2!3d19.6321094!4d-155.9903138!16s%2Fg%2F1tcw8cvn?entry=ttu){target="_black"}

    Address: 75-5852 Ali'i Dr, Kailua-Kona, HI 96740

We think this one is the best value for what it is. Standard room rates started at \$239/night.

-   [**Courtyard by Marriott King Kamehameha's Kona Beach Hotel**\
    ](https://www.google.com/maps/place/Courtyard+by+Marriott+King+Kamehameha's+Kona+Beach+Hotel/@19.6409608,-156.000091,17z/data=!3m1!4b1!4m9!3m8!1s0x79540ef8ced2d2b3:0x7be26046df281c3f!5m2!4m1!1i2!8m2!3d19.6409558!4d-155.9975161!16s%2Fg%2F1hc2c3zmd?entry=ttu){target="_black"}

    Address: 75-5660 Palani Rd, Kailua-Kona, HI 96740

This hotel is more expensive, with rates around \$400/night. They do have a little beach and it's also a Marriott property if you have points with the brand.

## 10-15 minute drive away:

-   [**Kanaloa at Kona by Outrigger**\
    ](https://www.google.com/maps/place/Kanaloa+at+Kona+by+Outrigger%C2%AE/@19.5648617,-155.9666575,18z/data=!3m1!4b1!4m9!3m8!1s0x795405e864539781:0xd0404fe9e18f795c!5m2!4m1!1i2!8m2!3d19.5648593!4d-155.9654541!16s%2Fg%2F1v_s625w?entry=ttu){target="_black"}

    Address: 78-261 Manukai St, Kailua-Kona, HI 96740

Waterfront condos. They have full kitchens. \$269/night for a 2 bed/2 bath\

-   [**Outrigger Kona Resort & Spa**\
    ](https://www.google.com/maps/place/OUTRIGGER+Kona+Resort+%26+Spa/@19.5738745,-155.9886955,13.73z/data=!3m1!5s0x795405c36b3aa019:0x4de21a6c74c0e45a!4m9!3m8!1s0x795405aabca420f1:0x631dd8cf4fa1aced!5m2!4m1!1i2!8m2!3d19.5586138!4d-155.9645948!16s%2Fg%2F11rxhtgwbk?entry=ttu){target="_black"}

    Address: 78-128 Ehukai St, Kailua-Kona, HI 96740

Room rates are around \$300 - \$400. They have a nice pool.

If you prefer to have a full kitchen during your stay, we also recommend looking into [**airbnb**](https://www.airbnb.com/){target="_black"} or [**vrbo**](https://www.vrbo.com/){target="_black"}. Please don't hesitate to reach out to us if you have any questions.
