---
title: "What Else to Do"
---
Bryan and Sara are planning to do the [Captain Cook reef snorkeling boat tour](https://www.konacoastboattours.com/captain-cook-reef-snorkeling){target="_blank"} 
with Kona Coast Boat Tour on April 22nd afternoon. Please join us if you are also
interested in snorkeling in Kealakekua Bay.

If you are planning to explore around the Big Island before or after the wedding, here are some links that could be useful. We have done some of the activities below ourselves, but some of the links are just the highly rated options from Google search.

## Car Rental

-   [Discount Hawaii Car Rental](https://www.discounthawaiicarrental.com/en-us/){target="_blank"}

-   [Autoslash Car Rental](https://www.autoslash.com/){target="_blank"}

## Things to Do

-   [Volcanoes National Park](https://www.nps.gov/havo/index.htm){target="_blank"}

-   Snorkeling

    -   [Kikaua Point Park](https://bigislandguide.com/kikaua-beach){target="_blank"} (kid-friendly), we checked this out ourselves and we love it.\
    -   Kealakekua Bay (by boat), [tour options on Tripadvisor](https://www.tripadvisor.com/Attractions-g60580-Activities-c42-Captain_Cook_Island_of_Hawaii_Hawaii.html){target="_blank"}
    -   [Night Snorkel with Manta Rays](https://konasnorkeltrips.com/snorkel-tours/manta-ray-snorkel-kona/){target="_blank"}, please Google for more options, there are so many

-   Beaches

    -   [Laʻaloa / White Sands Beach](https://bigislandguide.com/white-sands-beach-park-magic-sands){target="_blank"}
    -   [Maniniowali Beach](https://bigislandguide.com/maniniowali-beach-kua-bay){target="_blank"}
    -   [Hapuna Beach](https://dlnr.hawaii.gov/dsp/parks/hawaii/hapuna-beach-state-recreation-area/){target="_blank"}, entrance fee \$5 per person and parking fee \$10 per car
    -   [Spencer Beach Park](https://bigislandguide.com/samuel-m-spencer-beach-park){target="_blank"} (kid-friendly)

-   Coffee farm tours

    -   [Greenwell Farms tour](https://www.greenwellfarms.com/pages/big-island-kona-coffee-tours){targe="_blank"}, free guided tour
    -   [Heavenly Hawaiian Farms tour](https://heavenlyhawaiian.com/kona-coffee-farm-tour/){target="_blank"}

If you are looking for a comprehensive Big Island guide, we found a lot of great information on [The Hawaii Vacation Guide](https://thehawaiivacationguide.com/hawaii-big-island-travel-guide/){target="_blank"}. Have fun!
