---
title: "Ceremony & Reception"
---

## Where

[**Papa Kona Restaurant & Bar**](https://maps.app.goo.gl/677HX182K87oJH5TA){target="_blank"} <br>
**Address:** The Waterfront Row, 75-5770 Ali'i Dr 1st Floor, Kailua-Kona, HI 96740 <br>

**Ceremony:** The lawn out back at Papa Kona

**Reception:** 2nd floor lanai (cocktail hour followed by dinner, lawn games, and music) 

**Parking:** The on-site parking is on the expensive side (we read online it's $13/hour without validation). 
There is limited street parking along Ali'i drive or near the Kailua-Kona Public Library about a block away.

## When

Sunday April 21st, 2024

**Ceremony is at 4:30PM**, please arrive at Papa Kona by 4:10PM. There will be a
cocktail hour with passed appetizers, followed by a dinner buffet, lawn games and music. 
**The party ends at 10PM.**

**Attire:** Casual. E.g. Aloha (Hawaiian) shirts and sundresses

## The Day Before The Ceremony
We are hosting a welcome gathering at [**Ola Brew Co.**](https://maps.app.goo.gl/dUPGKs3xDBVJxnFY6){target="_blank"}
between 4:00 to 8:00PM. There will be food provided and a cash bar. 